# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSMS_entry_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from modules.utilities import *


class Ui_GS_Entry(object):
    def setupUi(self, GS_Entry):
        GS_Entry.setObjectName("GS_Entry")
        GS_Entry.resize(1051, 665)
        self.verticalLayout = QtWidgets.QVBoxLayout(GS_Entry)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QWidget(GS_Entry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Header.setStyleSheet("background-color: rgb(255, 215, 0);")
        self.Header.setObjectName("Header")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Header)
        self.gridLayout_2.setContentsMargins(12, 12, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.Header)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_12 = QtWidgets.QLabel(self.Header)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.Header)
        self.TabSelection = QtWidgets.QWidget(GS_Entry)
        self.TabSelection.setMinimumSize(QtCore.QSize(0, 50))
        self.TabSelection.setStyleSheet("")
        self.TabSelection.setObjectName("TabSelection")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TabSelection)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clientInfoBtn = QtWidgets.QPushButton(self.TabSelection)
        self.clientInfoBtn.setObjectName("clientInfoBtn")
        self.horizontalLayout_3.addWidget(self.clientInfoBtn)
        self.dataEntryBtn = QtWidgets.QPushButton(self.TabSelection)
        self.dataEntryBtn.setObjectName("dataEntryBtn")
        self.horizontalLayout_3.addWidget(self.dataEntryBtn)
        self.GenerateReportBtn = QtWidgets.QPushButton(self.TabSelection)
        self.GenerateReportBtn.setObjectName("GenerateReportBtn")
        self.horizontalLayout_3.addWidget(self.GenerateReportBtn)
        self.verticalLayout.addWidget(self.TabSelection)
        self.Main = QtWidgets.QWidget(GS_Entry)
        self.Main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Main.setObjectName("Main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Main)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ClientInfoPage = QtWidgets.QWidget()
        self.ClientInfoPage.setObjectName("ClientInfoPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ClientInfoPage)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.ClientInfoPage)
        self.widget.setEnabled(True)
        self.widget.setStyleSheet("QLineEdit {\n"
"    min-width: 500px; \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.clientName = QtWidgets.QLineEdit(self.widget)
        self.clientName.setMinimumSize(QtCore.QSize(502, 0))
        self.clientName.setObjectName("clientName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.clientName)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.date = QtWidgets.QLineEdit(self.widget)
        self.date.setObjectName("date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.time = QtWidgets.QLineEdit(self.widget)
        self.time.setObjectName("time")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.time)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.attention = QtWidgets.QLineEdit(self.widget)
        self.attention.setObjectName("attention")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.attention)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.addy1 = QtWidgets.QLineEdit(self.widget)
        self.addy1.setObjectName("addy1")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.addy1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.addy2 = QtWidgets.QLineEdit(self.widget)
        self.addy2.setObjectName("addy2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.addy2)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.addy3 = QtWidgets.QLineEdit(self.widget)
        self.addy3.setObjectName("addy3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.addy3)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.sampleType = QtWidgets.QLineEdit(self.widget)
        self.sampleType.setObjectName("sampleType")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.sampleType)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.sampleType2 = QtWidgets.QLineEdit(self.widget)
        self.sampleType2.setObjectName("sampleType2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.sampleType2)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.totalSamples = QtWidgets.QLineEdit(self.widget)
        self.totalSamples.setObjectName("totalSamples")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.totalSamples)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.recvtemp = QtWidgets.QLineEdit(self.widget)
        self.recvtemp.setObjectName("recvtemp")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.recvtemp)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.telephone = QtWidgets.QLineEdit(self.widget)
        self.telephone.setObjectName("telephone")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.telephone)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.email = QtWidgets.QLineEdit(self.widget)
        self.email.setObjectName("email")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.email)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.fax = QtWidgets.QLineEdit(self.widget)
        self.fax.setObjectName("fax")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.fax)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.payment = QtWidgets.QLineEdit(self.widget)
        self.payment.setObjectName("payment")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.payment)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.widget_2)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.ClientInfoPage)
        self.widget_4.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_4.setStyleSheet("QLineEdit {\n"
"    min-width: 400px; \n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_4)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.sample1Value = QtWidgets.QLineEdit(self.widget_4)
        self.sample1Value.setObjectName("sample1Value")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sample1Value)
        self.sample1Name = QtWidgets.QLabel(self.widget_4)
        self.sample1Name.setObjectName("sample1Name")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sample1Name)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.stackedWidget.addWidget(self.ClientInfoPage)
        self.ClientData = QtWidgets.QWidget()
        self.ClientData.setObjectName("ClientData")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ClientData)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.ClientData)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget.setStyleSheet("QTableView {\n"
"    color: black;\n"
"    gridline-color: black;\n"
"    border-color: rgb(242, 128, 133);\n"
"    font: 10px;\n"
"}\n"
"\n"
"QTableView::verticalHeaderItem {\n"
"    background-color: rgb(255, 137, 67);\n"
"    padding:20px; \n"
"}\n"
"\n"
"QTableView::indicator:checked {\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 1px;\n"
"    width: 7px;\n"
"    height: 7px;\n"
"    margin: 0px 5px 0 5px;\n"
"} \n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        #edited this 
        self.tableWidget.setColumnCount(6)
        
        total_items = len(GSMS_values)
        
        self.tableWidget.setRowCount(total_items)
        
        
        for x in range(total_items): 
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget.setVerticalHeaderItem(x, item)
        ''' 
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        '''

        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        
        #added this 
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        
        #this defines the column and row thing 
        for x in range(total_items): 
                self.tableWidget.setItem(x, 0, item)
                item = QtWidgets.QTableWidgetItem()

        for x in range(total_items): 
                self.tableWidget.setItem(x, 1, item)
                item = QtWidgets.QTableWidgetItem()                

        '''       
         
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        '''
        
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.ClientData)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.Main)

        self.retranslateUi(GS_Entry)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GS_Entry)

    def retranslateUi(self, GS_Entry):
        _translate = QtCore.QCoreApplication.translate
        GS_Entry.setWindowTitle(_translate("GS_Entry", "Form"))
        self.label_11.setText(_translate("GS_Entry", "GSMS Creation"))
        self.label_12.setText(_translate("GS_Entry", "Job Number: "))
        self.clientInfoBtn.setText(_translate("GS_Entry", "Client Information"))
        self.dataEntryBtn.setText(_translate("GS_Entry", "Data Entry"))
        self.GenerateReportBtn.setText(_translate("GS_Entry", "Generate Report "))
        self.label.setText(_translate("GS_Entry", "Client Name "))
        self.label_2.setText(_translate("GS_Entry", "Date"))
        self.label_3.setText(_translate("GS_Entry", "Time"))
        self.label_4.setText(_translate("GS_Entry", "Attention"))
        self.label_5.setText(_translate("GS_Entry", "Address 1"))
        self.label_6.setText(_translate("GS_Entry", "Address 2 "))
        self.label_7.setText(_translate("GS_Entry", "Address 3 "))
        self.label_8.setText(_translate("GS_Entry", "Sample Type "))
        self.label_9.setText(_translate("GS_Entry", "Sample Type 2 "))
        self.label_10.setText(_translate("GS_Entry", "Number of samples "))
        self.label_13.setText(_translate("GS_Entry", "Recieve Temp "))
        self.label_14.setText(_translate("GS_Entry", "Telephone "))
        self.label_15.setText(_translate("GS_Entry", "Email"))
        self.label_16.setText(_translate("GS_Entry", "Fax"))
        self.label_17.setText(_translate("GS_Entry", "Payment Information"))
        self.sample1Name.setText(_translate("GS_Entry", "Sample 1 Name:"))
       
       
        #does this onetime 
        total_items = len(GSMS_values) 
        
        for x in range(total_items): 
                print(x)
                item = self.tableWidget.verticalHeaderItem(x)
                item.setText(_translate("GS_Entry", str(x)))
                 
        
        ''' 
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("GS_Entry", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("GS_Entry", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("GS_Entry", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("GS_Entry", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("GS_Entry", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("GS_Entry", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("GS_Entry", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("GS_Entry", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("GS_Entry", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("GS_Entry", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("GS_Entry", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("GS_Entry", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("GS_Entry", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("GS_Entry", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("GS_Entry", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("GS_Entry", "16"))
        ''' 


        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("GS_Entry", "Property Name "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("GS_Entry", "UnitType "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("GS_Entry", "Ref Values "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("GS_Entry", "STD += 2"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("GS_Entry", "Sample 1 Value "))
       
        #added 
        item = self.tableWidget.horizontalHeaderItem(5) 
        item.setText(_translate("GS_Entry", "Sample 2 Value "))

        
         
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        
        counter = 0; 
        for key, value in GSMS_values.items(): 
                print(key, value )
                item = self.tableWidget.item(counter, 0)
                item.setText(_translate('GS_entry', value[0]))
                item = self.tableWidget.item(counter, 1)
                item.setText(_translate('GS_entry', value[1]))
                counter +=1;

  
                
        
        #data entry section that user will define 
        #item = self.tableWidget.item(0,1)
        #item.setText(_translate('GS_Entry', 'Test'))
        
        ''' 
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("GS_Entry", "Alkalinity"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("GS_Entry", "NH3-N "))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("GS_Entry", "CL-"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("GS_Entry", "Colour "))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("GS_Entry", "E.C"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("GS_Entry", "F-"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("GS_Entry", "TKN "))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("GS_Entry", "Mn"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("GS_Entry", "NO3-N "))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("GS_Entry", "N02-N"))
        item = self.tableWidget.item(10,0) 
        item.setText(_translate("GS_Entry", "Tommy")) 
        ''' 
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        
        #define buttons 
        self.clientInfoBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.ClientInfoPage))
        self.dataEntryBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.ClientData))
                
                
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GS_Entry = QtWidgets.QWidget()
    ui = Ui_GS_Entry()
    ui.setupUi(GS_Entry)
    GS_Entry.show()
    sys.exit(app.exec_())
